services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile_backend
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: musicstorm
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - '8000:8000'
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    ports:
      - '3000:3000'

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musicstorm
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./database/pgadmin-data:/var/lib/pgadmin
    ports:
      - '8080:80'
    depends_on:
      - database